openapi: 3.0.3
info:
  title: ECOMMERCE - NODEJS
  license:
    name: http://localhost:3000/
    url: http://localhost:3000/
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1/api
tags:
  - name: authentication
paths:
  /authentication/signup:
    post:
      tags:
        - authentication
      summary: Sign up a shop
      description: Sign up a shop
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
        required: true
      responses:
        "200":
          description: Sign up success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "registered success"
                  status:
                    type: number
                    example: 201
                  metadata:
                    $ref: "#/components/schemas/SignUpResponse"
  /authentication/login:
    post:
      tags:
        - authentication
      summary: Login a shop
      description: Login a shop
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        "200":
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "login success"
                  status:
                    type: number
                    example: 200
                  metadata:
                    $ref: "#/components/schemas/LoginResponse"
  /authentication/logout:
    post:
      tags:
        - authentication
      summary: Logout a shop
      description: Logout a shop
      operationId: logout
      security:
        - BearerAuth: []
        - x-api-key: []

      responses:
        "200":
          description: Logout success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "logout success"
                  status:
                    type: number
                    example: 200
                  metadata:
                    $ref: "#/components/schemas/LogoutResponse"
components:
  schemas:
    SignUpRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    SignUpResponse:
      type: object
      properties:
        shop:
          type: object
          properties:
            _id:
              type: string
            name:
              type: string
            email:
              type: string
        tokens:
          type: object
          properties:
            accessToken:
              type: string
            refreshToken:
              type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      properties:
        shop:
          type: object
          properties:
            _id:
              type: string
            name:
              type: string
            email:
              type: string
        tokens:
          type: object
          properties:
            accessToken:
              type: string
            refreshToken:
              type: string

    LogoutResponse:
      properties:
        acknowledged:
          type: boolean
        deletedCount:
          type: number

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
